apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: default
spec:
  selector:
    app: weather-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080